// Turn the committed trial-deck CSVs into one JSON the Worker can serve.
//
// The in-world panel has no deck of its own - it asks resopal for one. That means
// a deck has to be readable by something other than the bake pipeline, and it has
// to come back in the SAME flat shape as a booster pull, so the ProtoFlux parser
// in booster/ is one parser rather than two.
//
// Rarities are looked up in the committed pool snapshots so nothing here invents
// card data; a code with no snapshot entry is emitted with rarity TD, which is
// what the site's RANK already calls a trial-deck card.
//
//   node tools/build-decks.mjs
import { readFile, writeFile, readdir } from 'node:fs/promises';
import path from 'node:path';

const DATA = path.join(import.meta.dirname, '..', 'data');
const DECKS = [
  { id: 'td01', file: 'td01-red-blue.csv', set: 'TD01', name: 'Trial Deck — Red / Blue' },
  { id: 'td02', file: 'td02-green-purple.csv', set: 'TD02', name: 'Trial Deck — Green / Purple' },
];

// Every pool snapshot we have, so a deck listing a BP01 card still gets its rarity.
const rarityOf = new Map();
for (const f of await readdir(DATA)) {
  if (!/^pool-.*\.json$/.test(f)) continue;
  const pool = JSON.parse(await readFile(path.join(DATA, f), 'utf8'));
  for (const [rarity, list] of Object.entries(pool.byRarity))
    for (const e of list) if (!rarityOf.has(e.code)) rarityOf.set(e.code, rarity);
}

const out = { $comment: 'Generated by tools/build-decks.mjs from the committed CSVs. Do not hand-edit.', decks: {} };
for (const d of DECKS) {
  const text = await readFile(path.join(DATA, d.file), 'utf8');
  const cards = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#') || /^\s*quantity\s*,/i.test(line)) continue;
    const [q, code, ...rest] = line.split(',');
    if (!/^\d+$/.test(q.trim())) continue;
    cards.push({ n: +q, code: code.trim().toUpperCase(), name: rest.join(',').trim(), rarity: rarityOf.get(code.trim().toUpperCase()) || 'TD' });
  }
  const total = cards.reduce((t, c) => t + c.n, 0);
  out.decks[d.id] = { id: d.id, set: d.set, name: d.name, total, cards };
  console.log(`  ${d.id.padEnd(5)} ${String(total).padStart(3)} cards  ${cards.length} distinct  ${d.name}`);
}

await writeFile(path.join(DATA, 'decks.json'), JSON.stringify(out, null, 2) + '\n');
console.log(path.join(DATA, 'decks.json'));
